// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1cOWwRN38SW32aRkNNHKVpgNBTUNbJs',
    appId: '1:429589279697:web:0cd37656c8c570e6fe26f0',
    messagingSenderId: '429589279697',
    projectId: 'health-mob-38843',
    authDomain: 'health-mob-38843.firebaseapp.com',
    storageBucket: 'health-mob-38843.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBLLbLw0m69jBkuDtYFC6IzxqxieN-44Q',
    appId: '1:429589279697:android:6786e7559b512a7ffe26f0',
    messagingSenderId: '429589279697',
    projectId: 'health-mob-38843',
    storageBucket: 'health-mob-38843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZqpDJEnb445Rk6N6BedUmsmdDigwS3g',
    appId: '1:429589279697:ios:dc7093cbcfec64abfe26f0',
    messagingSenderId: '429589279697',
    projectId: 'health-mob-38843',
    storageBucket: 'health-mob-38843.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsZqpDJEnb445Rk6N6BedUmsmdDigwS3g',
    appId: '1:429589279697:ios:dc7093cbcfec64abfe26f0',
    messagingSenderId: '429589279697',
    projectId: 'health-mob-38843',
    storageBucket: 'health-mob-38843.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1cOWwRN38SW32aRkNNHKVpgNBTUNbJs',
    appId: '1:429589279697:web:3616cbc4eab5781afe26f0',
    messagingSenderId: '429589279697',
    projectId: 'health-mob-38843',
    authDomain: 'health-mob-38843.firebaseapp.com',
    storageBucket: 'health-mob-38843.firebasestorage.app',
  );
}
